# Q1 Python List vs Numpy Array
### expolaring the diffrenence between numpy vs python list from computational speed prospective

In [1]:
#------------------------------------
# Importing the necessrily libaries 
import numpy as np
import random as R
#------------------------------------

In [2]:
#------------------------------------
# Creating variables for testing
a1 = np.arange(15)
a5 = R.sample(range(1,100), 15)
#------------------------------------

print(a1)

print('\n')

print(a5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[36, 9, 56, 46, 95, 31, 91, 43, 10, 82, 29, 35, 37, 97, 34]


In [3]:
#------------------------------------

# numpy cubefunction
def cube_np(array):
    array_cube = np.power(array,3)
    return array_cube
#------------------------------------


#------------------------------------

# nlist cube function
def cube_list(List):
    return [ x**3 for x in List ]
#------------------------------------


#------------------------------------
# Testing both fucntions

a2 = cube_np(a1)
print(a2)

print('\n')
a3 = cube_list(a5)

print(a3)
#------------------------------------


#------------------------------------
# a NumPy array of 100,000 integer numbers
narray = np.random.randint(low=1, high=100, size=100000)
#------------------------------------
# a nlist a Python list of 100,000 integer numbers
nlist = [R.randint(0, 100) for x in range(1, 100001)]
#------------------------------------

[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744]


[46656, 729, 175616, 97336, 857375, 29791, 753571, 79507, 1000, 551368, 24389, 42875, 50653, 912673, 39304]


## Q2 Measuring the speed of both fucntions. 

In [4]:
%timeit cube_np(narray)

234 µs ± 2.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit cube_list(nlist)

18.3 ms ± 163 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Numpy array is signfically faster than python list. 
#### One should always consider to leverage the computation advantage of numpy arrays during machine learning workflow.
#### the reason for the difference is how data is being stored

# Q3 Array manipulations.

In [6]:
#------------------------------------
# 1D array converted to 2D array shaped to (4,5)
D2_array = np.arange(20).reshape(4,5)
#------------------------------------

#------------------------------------
# coverting it back to 1D
D1_array = D2_array.flatten()
#------------------------------------

In [7]:
#------------------------------------
# creating Array A
array_A = np.array([[1,2],[3,4]])
#------------------------------------

#------------------------------------
# Creating Array B
array_B = np.array([[5,6,7],[8,9,10]])
#------------------------------------

print('Array B is')
print(array_B)

Array B is
[[ 5  6  7]
 [ 8  9 10]]


In [8]:
#------------------------------------
# slice to add 
array_B_slice1 = array_B[:2, 2:]
#------------------------------------

#------------------------------------
# Slice to multiply
array_B_slice2 = array_B[:2, :2] 
#------------------------------------

#------------------------------------
print(array_B_slice1)
print('\n')
print(array_B_slice2)
print('\n')
#------------------------------------

#------------------------------------
# multiply slice2 with array A then add slice 1 
A_mul_B = np.hstack([np.multiply(array_B_slice2, array_A),array_B_slice1]) 
#------------------------------------
print(A_mul_B)

[[ 7]
 [10]]


[[5 6]
 [8 9]]


[[ 5 12  7]
 [24 36 10]]
