In [6]:
import numpy as np
import random as R

In [18]:
a1 = np.arange(15)
#print (a1)
EX = R.sample(range(1,100), 15)
print(EX)


TypeError: choice() takes 2 positional arguments but 3 were given

In [21]:
def cube_np(array):
    array_cube = np.power(array,3)
    return array_cube

def cube_list(List):
    return [ x**3 for x in List ]

a2 = cube_np(a1)
#print(a2)

a3 = cube_list(EX)
#print(a3)

narray = np.random.randint(low=1, high=100, size=100000)
nlist = [R.randint(0, 100) for x in range(1, 100001)]


100000

In [22]:
%timeit cube_np(narray)

235 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit cube_list(nlist)

17.9 ms ± 88.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
D2_array = np.arange(20).reshape(4,5)
D1_array = D2_array.flatten()


In [49]:
array_A = np.array([[1,2],[3,4]])
array_B = np.array([[5,6,7],[8,9,10]])

print(array_B)

[[ 5  6  7]
 [ 8  9 10]]


In [69]:
array_B_slice = array_B[:2, 2:]
array_B_slice2 = array_B[:2, :2] 

print(array_B_slice)
print('\n')
print(array_B_slice2)
print('\n')

A_mul_B = np.hstack([np.multiply(array_B_slice2, array_A),array_B_slice]) 
print(A_mul_B)

[[ 7]
 [10]]


[[5 6]
 [8 9]]


[[ 5 12  7]
 [24 36 10]]
