In [2]:
#------------------------------------
# Importing the necessrily libaries 
import numpy as np
import random as R
#------------------------------------

In [5]:
#------------------------------------
# Creating variables for testing
a1 = np.arange(15)
a5 = R.sample(range(1,100), 15)
#------------------------------------

print(a1)

print('\n')

print(a5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[24, 88, 66, 34, 83, 32, 2, 6, 89, 56, 97, 46, 80, 25, 60]


In [6]:
#------------------------------------

# numpy cubefunction
def cube_np(array):
    array_cube = np.power(array,3)
    return array_cube
#------------------------------------


#------------------------------------

# nlist cube function
def cube_list(List):
    return [ x**3 for x in List ]
#------------------------------------


#------------------------------------
# Testing both fucntions

a2 = cube_np(a1)
print(a2)

print('\n')
a3 = cube_list(a5)

print(a3)
#------------------------------------


#------------------------------------
# a NumPy array of 100,000 integer numbers
narray = np.random.randint(low=1, high=100, size=100000)
#------------------------------------
# a nlist a Python list of 100,000 integer numbers
nlist = [R.randint(0, 100) for x in range(1, 100001)]
#------------------------------------

[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744]


[13824, 681472, 287496, 39304, 571787, 32768, 8, 216, 704969, 175616, 912673, 97336, 512000, 15625, 216000]


In [22]:
%timeit cube_np(narray)

235 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit cube_list(nlist)

17.9 ms ± 88.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
#------------------------------------
# 1D array converted to 2D array shaped to (4,5)
D2_array = np.arange(20).reshape(4,5)
#------------------------------------

#------------------------------------
# coverting it back to 1D
D1_array = D2_array.flatten()
#------------------------------------

In [49]:
array_A = np.array([[1,2],[3,4]])
array_B = np.array([[5,6,7],[8,9,10]])

print(array_B)

[[ 5  6  7]
 [ 8  9 10]]


In [69]:
array_B_slice = array_B[:2, 2:]
array_B_slice2 = array_B[:2, :2] 

print(array_B_slice)
print('\n')
print(array_B_slice2)
print('\n')

A_mul_B = np.hstack([np.multiply(array_B_slice2, array_A),array_B_slice]) 
print(A_mul_B)

[[ 7]
 [10]]


[[5 6]
 [8 9]]


[[ 5 12  7]
 [24 36 10]]
